export const Tuningmenu_Events = {
    PREVIEW_TUNING: 'TuningMenu:Preview:Tuning',
    PREVIEW_TUNING_PLATE: 'TuningMenu:Preview::Plate',
    PREVIEW_TUNING_WINDOWTINT: 'TuningMenu:Preview:Windowtint',
    PREVIEW_TUNING_STANCE: 'TuningMenu:Preview:Stance',
    PREVIEW_TUNING_OPTICS: 'TuningMenu:Preview:Optics',
    PREVIEW_TUNING_INTERIOR: 'TuningMenu:Preview:Interior',
    PREVIEW_TUNING_WHEELS: 'TuningMenu:Preview:Wheels',
    OPEN: 'TuningMenu:Open',
    PURCHASE: 'TuningMenu:Purchase:Tuning',
    PURCHASE_PLATE: 'TuningMenu:Purchase:Plate',
    PURCHASE_WINDOWTINT: 'TuningMenu:Purchase:Windowtint',
    PURCHASE_STANCE: 'TuningMenu:Purchase:Stance',
    PURCHASE_OPTICS: 'TuningMenu:Purchase:Optics',
    PURCHASE_INTERIOR: 'TuningMenu:Purchase:Interior',
    PURCHASE_WHEELS: 'TuningMenu:Purchase:Wheels',
    CLOSE: 'TuningMenu:Close',
    CLIENT: 'TuningMenu:Client',
    SERVER: 'TuningMenu:Server',
};